/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.18.6.0 (NJsonSchema v9.10.67.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
import * as moment from 'moment';
var EndpointMessageQueue = /** @class */ (function () {
    function EndpointMessageQueue(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    EndpointMessageQueue.prototype.init = function (data) {
        if (data) {
            this.rand = data["Rand"] !== undefined ? data["Rand"] : null;
            this.endpoint = data["Endpoint"] ? EndpointInfo.fromJS(data["Endpoint"]) : null;
            if (data["Content"] && data["Content"].constructor === Array) {
                this.content = [];
                for (var _i = 0, _a = data["Content"]; _i < _a.length; _i++) {
                    var item = _a[_i];
                    this.content.push(EndpointMessage.fromJS(item));
                }
            }
        }
    };
    EndpointMessageQueue.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new EndpointMessageQueue();
        result.init(data);
        return result;
    };
    EndpointMessageQueue.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["Rand"] = this.rand !== undefined ? this.rand : null;
        data["Endpoint"] = this.endpoint ? this.endpoint.toJSON() : null;
        if (this.content && this.content.constructor === Array) {
            data["Content"] = [];
            for (var _i = 0, _a = this.content; _i < _a.length; _i++) {
                var item = _a[_i];
                data["Content"].push(item.toJSON());
            }
        }
        return data;
    };
    EndpointMessageQueue.prototype.clone = function () {
        var json = this.toJSON();
        var result = new EndpointMessageQueue();
        result.init(json);
        return result;
    };
    return EndpointMessageQueue;
}());
export { EndpointMessageQueue };
var EndpointInfo = /** @class */ (function () {
    function EndpointInfo(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    EndpointInfo.prototype.init = function (data) {
        if (data) {
            this.installationId = data["InstallationId"] !== undefined ? data["InstallationId"] : null;
            this.deviceId = data["DeviceId"] !== undefined ? data["DeviceId"] : null;
            this.appIdentifier = data["AppIdentifier"] !== undefined ? data["AppIdentifier"] : null;
            this.appVersion = data["AppVersion"] !== undefined ? data["AppVersion"] : null;
            this.environment = data["Environment"] ? Environment.fromJS(data["Environment"]) : null;
        }
    };
    EndpointInfo.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new EndpointInfo();
        result.init(data);
        return result;
    };
    EndpointInfo.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["InstallationId"] = this.installationId !== undefined ? this.installationId : null;
        data["DeviceId"] = this.deviceId !== undefined ? this.deviceId : null;
        data["AppIdentifier"] = this.appIdentifier !== undefined ? this.appIdentifier : null;
        data["AppVersion"] = this.appVersion !== undefined ? this.appVersion : null;
        data["Environment"] = this.environment ? this.environment.toJSON() : null;
        return data;
    };
    EndpointInfo.prototype.clone = function () {
        var json = this.toJSON();
        var result = new EndpointInfo();
        result.init(json);
        return result;
    };
    return EndpointInfo;
}());
export { EndpointInfo };
var EndpointMessage = /** @class */ (function () {
    function EndpointMessage(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    EndpointMessage.prototype.init = function (data) {
        if (data) {
            this.timestamp = data["Timestamp"] ? moment(data["Timestamp"].toString()) : null;
            this.appEvent = data["AppEvent"] ? EndpointAppEvent.fromJS(data["AppEvent"]) : null;
            this.logEvent = data["LogEvent"] ? EndpointLogEvent.fromJS(data["LogEvent"]) : null;
            this.metricEvent = data["MetricEvent"] ? EndpointMetricEvent.fromJS(data["MetricEvent"]) : null;
        }
    };
    EndpointMessage.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new EndpointMessage();
        result.init(data);
        return result;
    };
    EndpointMessage.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["Timestamp"] = this.timestamp ? this.timestamp.toISOString() : null;
        data["AppEvent"] = this.appEvent ? this.appEvent.toJSON() : null;
        data["LogEvent"] = this.logEvent ? this.logEvent.toJSON() : null;
        data["MetricEvent"] = this.metricEvent ? this.metricEvent.toJSON() : null;
        return data;
    };
    EndpointMessage.prototype.clone = function () {
        var json = this.toJSON();
        var result = new EndpointMessage();
        result.init(json);
        return result;
    };
    return EndpointMessage;
}());
export { EndpointMessage };
var Environment = /** @class */ (function () {
    function Environment(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    Environment.prototype.init = function (data) {
        if (data) {
            this.platform = data["Platform"] !== undefined ? data["Platform"] : null;
            this.architectureIdentifier = data["ArchitectureIdentifier"] !== undefined ? data["ArchitectureIdentifier"] : null;
            this.runtimeIdentifier = data["RuntimeIdentifier"] !== undefined ? data["RuntimeIdentifier"] : null;
            this.oSVersion = data["OSVersion"] !== undefined ? data["OSVersion"] : null;
            this.address = data["Address"] !== undefined ? data["Address"] : null;
        }
    };
    Environment.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new Environment();
        result.init(data);
        return result;
    };
    Environment.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["Platform"] = this.platform !== undefined ? this.platform : null;
        data["ArchitectureIdentifier"] = this.architectureIdentifier !== undefined ? this.architectureIdentifier : null;
        data["RuntimeIdentifier"] = this.runtimeIdentifier !== undefined ? this.runtimeIdentifier : null;
        data["OSVersion"] = this.oSVersion !== undefined ? this.oSVersion : null;
        data["Address"] = this.address !== undefined ? this.address : null;
        return data;
    };
    Environment.prototype.clone = function () {
        var json = this.toJSON();
        var result = new Environment();
        result.init(json);
        return result;
    };
    return Environment;
}());
export { Environment };
var EndpointAppEvent = /** @class */ (function () {
    function EndpointAppEvent(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    EndpointAppEvent.prototype.init = function (data) {
        if (data) {
            this.appVersion = data["AppVersion"] !== undefined ? data["AppVersion"] : null;
            this.type = data["Type"] !== undefined ? data["Type"] : null;
        }
    };
    EndpointAppEvent.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new EndpointAppEvent();
        result.init(data);
        return result;
    };
    EndpointAppEvent.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["AppVersion"] = this.appVersion !== undefined ? this.appVersion : null;
        data["Type"] = this.type !== undefined ? this.type : null;
        return data;
    };
    EndpointAppEvent.prototype.clone = function () {
        var json = this.toJSON();
        var result = new EndpointAppEvent();
        result.init(json);
        return result;
    };
    return EndpointAppEvent;
}());
export { EndpointAppEvent };
var EndpointLogEvent = /** @class */ (function () {
    function EndpointLogEvent(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    EndpointLogEvent.prototype.init = function (data) {
        if (data) {
            this.identifier = data["Identifier"] !== undefined ? data["Identifier"] : null;
            this.content = data["Content"] ? VariantValue.fromJS(data["Content"]) : null;
            this.details = data["Details"] !== undefined ? data["Details"] : null;
        }
    };
    EndpointLogEvent.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new EndpointLogEvent();
        result.init(data);
        return result;
    };
    EndpointLogEvent.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["Identifier"] = this.identifier !== undefined ? this.identifier : null;
        data["Content"] = this.content ? this.content.toJSON() : null;
        data["Details"] = this.details !== undefined ? this.details : null;
        return data;
    };
    EndpointLogEvent.prototype.clone = function () {
        var json = this.toJSON();
        var result = new EndpointLogEvent();
        result.init(json);
        return result;
    };
    return EndpointLogEvent;
}());
export { EndpointLogEvent };
var EndpointMetricEvent = /** @class */ (function () {
    function EndpointMetricEvent(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    EndpointMetricEvent.prototype.init = function (data) {
        if (data) {
            this.identifier = data["Identifier"] !== undefined ? data["Identifier"] : null;
            this.value = data["Value"] !== undefined ? data["Value"] : null;
        }
    };
    EndpointMetricEvent.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new EndpointMetricEvent();
        result.init(data);
        return result;
    };
    EndpointMetricEvent.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["Identifier"] = this.identifier !== undefined ? this.identifier : null;
        data["Value"] = this.value !== undefined ? this.value : null;
        return data;
    };
    EndpointMetricEvent.prototype.clone = function () {
        var json = this.toJSON();
        var result = new EndpointMetricEvent();
        result.init(json);
        return result;
    };
    return EndpointMetricEvent;
}());
export { EndpointMetricEvent };
var VariantValue = /** @class */ (function () {
    function VariantValue(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    VariantValue.prototype.init = function (data) {
        if (data) {
            this.boolValue = data["BoolValue"] !== undefined ? data["BoolValue"] : null;
            this.numberValue = data["NumberValue"] !== undefined ? data["NumberValue"] : null;
            this.dateTimeValue = data["DateTimeValue"] ? moment(data["DateTimeValue"].toString()) : null;
            this.stringValue = data["StringValue"] !== undefined ? data["StringValue"] : null;
        }
    };
    VariantValue.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new VariantValue();
        result.init(data);
        return result;
    };
    VariantValue.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["BoolValue"] = this.boolValue !== undefined ? this.boolValue : null;
        data["NumberValue"] = this.numberValue !== undefined ? this.numberValue : null;
        data["DateTimeValue"] = this.dateTimeValue ? this.dateTimeValue.toISOString() : null;
        data["StringValue"] = this.stringValue !== undefined ? this.stringValue : null;
        return data;
    };
    VariantValue.prototype.clone = function () {
        var json = this.toJSON();
        var result = new VariantValue();
        result.init(json);
        return result;
    };
    return VariantValue;
}());
export { VariantValue };
var EndpointManifest = /** @class */ (function () {
    function EndpointManifest(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    EndpointManifest.prototype.init = function (data) {
        if (data) {
            this.endpoint = data["Endpoint"] ? EndpointInfo.fromJS(data["Endpoint"]) : null;
            this.configuration = data["Configuration"] !== undefined ? data["Configuration"] : null;
            this.appInfo = data["AppInfo"] ? AppInfo.fromJS(data["AppInfo"]) : null;
        }
    };
    EndpointManifest.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new EndpointManifest();
        result.init(data);
        return result;
    };
    EndpointManifest.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["Endpoint"] = this.endpoint ? this.endpoint.toJSON() : null;
        data["Configuration"] = this.configuration !== undefined ? this.configuration : null;
        data["AppInfo"] = this.appInfo ? this.appInfo.toJSON() : null;
        return data;
    };
    EndpointManifest.prototype.clone = function () {
        var json = this.toJSON();
        var result = new EndpointManifest();
        result.init(json);
        return result;
    };
    return EndpointManifest;
}());
export { EndpointManifest };
var AppInfo = /** @class */ (function () {
    function AppInfo(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    AppInfo.prototype.init = function (data) {
        if (data) {
            this.hasUpdate = data["HasUpdate"] !== undefined ? data["HasUpdate"] : null;
        }
    };
    AppInfo.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new AppInfo();
        result.init(data);
        return result;
    };
    AppInfo.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["HasUpdate"] = this.hasUpdate !== undefined ? this.hasUpdate : null;
        return data;
    };
    AppInfo.prototype.clone = function () {
        var json = this.toJSON();
        var result = new AppInfo();
        result.init(json);
        return result;
    };
    return AppInfo;
}());
export { AppInfo };
export var EndpointAppEventType;
(function (EndpointAppEventType) {
    EndpointAppEventType["Install"] = "Install";
    EndpointAppEventType["Update"] = "Update";
    EndpointAppEventType["Uninstall"] = "Uninstall";
})(EndpointAppEventType || (EndpointAppEventType = {}));
var SwaggerException = /** @class */ (function (_super) {
    __extends(SwaggerException, _super);
    function SwaggerException(message, status, response, headers, result) {
        var _this = _super.call(this) || this;
        _this.isSwaggerException = true;
        _this.message = message;
        _this.status = status;
        _this.response = response;
        _this.headers = headers;
        _this.result = result;
        return _this;
    }
    SwaggerException.isSwaggerException = function (obj) {
        return obj.isSwaggerException === true;
    };
    return SwaggerException;
}(Error));
export { SwaggerException };
function throwException(message, status, response, headers, result) {
    throw new SwaggerException(message, status, response, headers, result);
}
//# sourceMappingURL=IClientService.js.map